### ISSUE TITLE
Getting Error: spawn ENOTDIR when using download command

### ISSUE THREAD

**Issue by YewTreeWeb** [Shopify/node-themekit#41]
Hi,

I'm using @shopify/themekit in combination with Gulp. I have been able to use the get command but when trying the download I get the error `Error: spawn ENOTDIR`. I've been trying different flags and options but nothing. My task is:
```
export const download = done => {
    themeKit.command('download', {
        env: 'development',
        dir: 'src/'
    }, {
        cwd: 'config/config.yml',
        logLevel: 'all'
    }).catch(err => console.error('Error', err));
    done();
};
```
When I run it the full error displayed is:
```
[10:50:09] Starting 'download'...
[10:50:09] Finished 'download' after 7.48 ms
Error { Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Promise (/Users/mat/Sites/shopify/shopify-kit/node_modules/@shopify/themekit/lib/run-executable.js:22:26)
    at new Promise (<anonymous>)
    at runExecutable (/Users/mat/Sites/shopify/shopify-kit/node_modules/@shopify/themekit/lib/run-executable.js:15:10)
    at Object.command (/Users/mat/Sites/shopify/shopify-kit/node_modules/@shopify/themekit/lib/themekit.js:20:12)
    at command (/Users/mat/Sites/shopify/shopify-kit/gulpfile.babel.js:53:14)
    at taskWrapper (/Users/mat/Sites/shopify/shopify-kit/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12) errno: 'ENOTDIR', code: 'ENOTDIR', syscall: 'spawn' }
```
Any help with this would be much appreciated. 

Thanks

**Comment by YewTreeWeb** [comment]
I realised I was not pointing to a config.yml but to a custom shopify.yml. So finally managed to resolve it.
